### ISSUE TITLE
Level description

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#1]
ამჟამად Level-ების არჩევისას სასურველი Level-ის შესაბამისი ღილაკის დაჭერისთანავე იწყება თამაში. თქვენი დავალებაა Level-ების არჩევა შეცვალოთ შემდეგნაირად.

```
    [1]  Level 1    
  * [2]  Level 2
    [3]  Level 3

   Description: In level 2 you must avoid poisoned food.

   Press ENTER to start.
```

ლეველის შესაბამისი ღილაკის დაჭერისას არ უნდა იწყებოდეს თამაში ავტომატურად.
ამის სანაცვლოდ თუ დავაჭერთ 2 გამოჩნდება ვარსკვლავი Level 2 ის გასწვრივ.
ამასთანავე ქვემოთ გამოჩნდება ლეველის შესაბამისი ვრცელი აღწერა. 
არჩეული ლეველის შეცვლა შეიძლება სხვა ციფრის დაჭერით.
თამაში იწყება მხოლოდ Enter-ის დაჭერის შემდეგ,

ამისათვის:
1. გააფართოვეთ Level. დაუმატეთ getDescription()
2. გააფართოვეთ LevelPresenter და LevelView 
ყურადრება! Description-ის გადასაცემად არ გამოიყენოთ იგივე მექანიზმი რაც გამოყენებულია სახელის მოდელიდან ვიუზე გადასაცემად. შემდეგი ურთიერთობის სქემა უნდა იქნას იმპლემენტირებულის. LevelPresenter -ი გამოიძახებს getDescription()-ს მოდელზე მხოლოდ მას მერე რაც Level-ი იქნე არჩეული. Description-ის ცვლილება გაეგზავნება View-ს Observer-ის გამოყენებით. იხ. აღწერა [Model-view-presenter კლასების ურთიერთქმედება](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki#model-view-presenter-%E1%83%99%E1%83%9A%E1%83%90%E1%83%A1%E1%83%94%E1%83%91%E1%83%98%E1%83%A1-%E1%83%A3%E1%83%A0%E1%83%97%E1%83%98%E1%83%94%E1%83%A0%E1%83%97%E1%83%A5%E1%83%9B%E1%83%94%E1%83%93%E1%83%94%E1%83%91%E1%83%90)

მაგალითისათვის შეგიძლიათ გაეცნოთ CellUpdateListener-ის გამოყენებას.

კითხვები:
1. გაეცით კითხვა 1.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by gati3478** [comment]
საბოლოოდ გადავწყვიტე რომ ობზერვერმა LevelView-ს დაავალოს ლეველის აღწერის დახატვა, მაგ შემთხვევაში ჩემი აზრით უფრო ზოგადი კოდი გამოვა, რომელიც LevelView-ს კონკრეტულ იმპლემენტაციაზე არ იქნება დამოკიდებული (ანუ ობზერვერმა არ იცის Terminal ობიექტით ხდება ხატვა თუ რაიმე სხვა გრაფიკული კომპონენტით).

**Comment by gmamaladze** [comment]
@gati3478 
დავალება: 50
კითხვები: 30
შედარება: 20
ჯამი: 100
