### ISSUE TITLE
Huge map

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#13]
ამჟამინდელ იმპლემენტაციაში ეკრანის რაზმერი და დაფის რაზმერი იდენტურია.

წარმოიდგინეთ რომ დაფა 5 ჯერ აღემატება სიგრძეშიც და სიგანეშიც ეკრანის ზომას.
ეკრანი - ანუ ის არე რომელიც იხატება შეძლებს დროის ნებისმიერ მომენტში მხოლოდ მთელი დაფის მეხუთედის ჩვენებას. თქვენი მიზანია მოახდინოთ პროგრამის მოდიფიკაცია ისე რომ ეკრანი კამერასავით დასდევდეს გველს და აჩვენებდეს შესაბამის არეს გველის გარშემო.

ყურადღება! ამ ამოცანის რეალიზაცია წესით საკმაოდ მარტივია და არ უნდა დასჭირდეს ბევრი მოდიფიკაცია. ამოცანის მთავარი სირთულეა მიხვდეთ სად და როგორ იქნება ყველაზე ბუნებრივი და მიზანშეწონილი შესაბამისი ცვლილების შეტანა.

კითხვები:
1. გაეცით კითხვა 13.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by Meravici** [comment]
ერთი კიდიდან მეორე კიდეში გასვლა კამერის მოძრაობაზე როგორ უნდა აისახოს?

კამერა უნდა გადახტეს ერთი ბოლოდან მეორეში თუ ისე უნდა გამოჩნდეს ყველაფერი თითქოს გველი არც გასულა დაფის ბოლოში?

**Comment by gmamaladze** [comment]
კიდე ამ შემთხვევაში პირობითი ხდება. ანუ თითქოს არც გასულა, თითქოს სფეროზე მოძრაობს.

**Comment by gmamaladze** [comment]
@giogog - გთხოვთ ამოცანასთან დაკავშირებული კითხვები დასხვათ Piazza-ზე. იქ უფრო სწრაფად ვახერხებ რეაგირებას.

**Comment by gmamaladze** [comment]
@giogog  - ამოცანის პირობაში როგორც ეწერა რთული იყო ამ მოდიფიკაციისათვის სწორი ადგილის პოვნა. სინამდვილეში საჭირო იყო GameFacade-ის ClippedGameFacade-ით ჩანაცვლება.
იხილეთ კომიტი 29bbd5f . დანარჩენი ცვლილებები მხოლოდ ელეგანტური ინჯექშენისთვისაა საჭირო. თქვენ რომც ჩაგენაცვლებინათ ოკ. იყო.

**Comment by gmamaladze** [comment]
@giogog დასატესტირებლათ გაუშვით HugeMapApp და ამოირჩიეთ მაგალითად Wormhole. იმოძრავეთ დაფაზე და მოძებნეთ Wormhole-ები.

**Comment by gmamaladze** [comment]
დავალება: 20 იხ.: 29bbd5f
კითხვები: 30
შედარება: 20
ჯამი: 70
