### ISSUE TITLE
Escaping Mouse

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#14]
ამჟამად თაგვი იქვე რჩება სადაც გაჩნდება მანამ სანამ გველი არ შეჭამს.
თქვენი ამოცანაა შექმნათ ახალი ლეველი რომელშიც თამაშის დაწყებიდანვე
გველის გარდა გაჩნდება 5 თაგვი. თაგვი უძრავია სანამ მას რაიმე არ მიუახლოვდება სხვა არსება (მაგალითად გველი) 5 უჯრის მანძილზე. მაშინ თაგვი იწყებს გაქცევას, ანუ ცდილობს ისეთი მიმართულება აირჩიოს რომ დაშორდეს სხვა არსებას. თაგვი გველზე ნელია და ორ სვლაში ერთ ნაბიჯს აკეთებს. შეჭმის შემდეგ ჩნდება ახალი თაგვი ახალ პოზიციაზე. თაგვი არამარტო გველს არამედ ყველა სხვა არსებასაც გაურბის , მათ შორის სხვა თაგვსაც. გაითვალისტინეთ რომ თაგვის 5 უჯრის რადიუსში შეიძლება ერთზე მეტი არსება იმყოფებოდეს, მაშინ ყველაზე ხელსაყრელი მიმართულება უნდა იქნას არჩეული გასაქცევად.
1. დაამატეთ EscapingMouseBeing  - მოიფიქრეთ რომელ კლასებს აირჩევთ მშობელ კლასად.
2. დაამატეთ შესაბამისი Populator-ი - მოიფიქრეთ რომელ კლასებს აირჩევთ მშობელ კლასად.
3. შექმენით ახალი ლეველი, დასახელებით "Tom and Jerry"  და დაამატეთ App-ში შესაბამის ადგილზე.
- მოიფიქრეთ რა მეთოდშია ყველაზე მოსახერხებელი იმის დადგენა მოგიახლოვდა თუ არა ვინმდე და გასაქცევი მიმართულების შეცვლა.
- წესით დავალების რეალიზაცია საკმაოდ მარტივია და არ უნდა დაგჭირდეთ სხვა კლასების ცვლილება.

კითხვები:
1. გაეცით კითხვა 14.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by gmamaladze** [comment]
@ikoba12 
დავალება: 20 - იხ. მომდევნო კომენტარები, იხ.: 46ac28ab613d8683da45b6919815eb6b2fc76734
კითხვები: 30
შედარება: 20
ჯამი: 70

**Comment by ikoba12** [comment]
ბატონო გიორგი აშკარად ვიკიში დავწერე აღწერა და რამე საშუალება არის რომ შემოწმდეს ეგ?

**Comment by ikoba12** [comment]
და კიდევ 1 ნაწილში რა შეცდომა მაქ ზუსტად რომ მითხრათ ეგეც თუ შეიძლება

**Comment by gmamaladze** [comment]
@ikoba12  - ვიკის რევიჟენ ჰისტორი ვნახე აქ. 
https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1/_history
თქვენი კონრიბიუშენიც ჩანს. წავიკითხავ და გავითვალისწინებ.

**Comment by gmamaladze** [comment]
ბოდიში ჩემი შეცდომაა ვერ დავინახე. კიდევ ერთხელ ვნახავ ყურადღებით.

**Comment by ikoba12** [comment]
მადლობა და პირველ ნაწილშიც უფრო დეტალურად რომ მითხრათ რა შეცდომა მაქვს რომ მომავალში აღარ გავიმეორო კარგი იქნება

**Comment by gmamaladze** [comment]
@ikoba12
1. Pull request-ი არ გაგიკეთებიათ.
2. მთავარი კლასის დასახელება არ შეესაბამებოდა დავალების მოცემულობას. (ამ ფაქტმა მაფიქრებინა რომ იმპლემენტაცია არასრული იყო ) იხ.: 46ac28ab613d8683da45b6919815eb6b2fc76734
3. საბაზო კლასის არჩევასთან დაკავშირებულ მსჯელობას არ ვეთანხმები. იხ.: 46ac28ab613d8683da45b6919815eb6b2fc76734
4. გაქცევის ლოგიკა არასწორად მუშაობს დაფის საზღვრებზე, რადგან არ ითვალისწინებს ტოპოლოგიას. არ შემისწორებია.

შეფასებას დავაკორექტირებ.

**Comment by ikoba12** [comment]
თქვენ რომ გიწერიათ setDirection(Direction.DOWN); ეს იმისთვისაა, რომ MovingBeing კლასში ერორი არ ამოვარდეს თუ არ მოგვიახლოვდა 5 უჯრაზე არავინ ხომ ასეა?

**Comment by ikoba12** [comment]
ეგ მომეჩვენა არასწორად. რახან ყოველ ჯერზე აუცილებელი Direction განსაზღვრული ყოფილიყო და არ ყოფილიყო ნული ჩავთვალე რომ რანდომად დავუსეტო ნებისმიერი Direction და შემდეგ moveTo-ს ლოგიკაში გავიტანო შემოწმება როგორც თქვენ გაქვთ არასწორად მომეჩვენა. და მთავარი move მეთოდის გადათვირთვა რომ არ შეიძლებოდა შემდეგ ვიფიქრე და უფრო ლოგიკურადაც მომეჩვენა რომ ჩემი თაგვი რახან ყოველ ჯერზე არ მოძრაობს არ უნდა ყოფილიყო MovingBeing-ის შვილობილი, რომელმაც ყოველ სვლაზე უნდა იცოდეს რომელ Direction-ის მიმართულებით უნდა იმოძრავოს. თავიდან მაგ კლასის შვილობილი იყო და EscapingMouseBeing ერქვა შემდეგ განსხვავებულად ვცადე და წინა კლასი არ წამიშლია და მაგიტომ მოხდა სახელების არევა საბოლოო ვარიანტი კიდე უბრალოდ აღარ გადამიკოპირებია და პირდაპირ EscapingMouseBeing კლასი წავშალე და მეორე დავტოვე  ვიფიქრე ეგ არ იყო მნიშვნელოვანი დავალებაში.

**Comment by ikoba12** [comment]
ტოპოლოგიას რაც შეეხება მაგაზე არ მაქვს კითხვა ეგ უბრალოდ გამომეპარა
