### ISSUE TITLE
Swap sides

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#20]
მთავარი იდეა: მომხმარებელი მართავს თაგვს. კომპიუტერის მიერ მართული გველი დასდევს თაგვს. გველი უნდა მოძრაობდეს (სასურველია უმოკლესი გზით) თაგვის მიმართულებით. გველი თუ შეჭამს თაგვს თამაში არ წყდება. თაგვი ჩნდება სხვა ადგილას. თამაშის შეწყვეტა ხდება ESC ღილაკით.
1. მთავარი სირთულე იმაშია რომ გველს არ აქვს და არც უნდა ქონდეს წვდომა Universe-ზე და თაგვზე.
2. გამოიყენეთ Observer პატერნი. თაგვი უნდა იყოს Observable. გველი Observer-ი რომელიც თაგვის გადაადგილებას აკვირდება.
3. მოიფიქრეთ სად იქნება ყველაზე ხელსაყრელი Observable-ის attach detach მეთოდების გამოძახება.

კითხვები:
1. გაეცით კითხვა 20.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by gmamaladze** [comment]
@nikagogibedashvili
დავალება: 10 - პროცესი დაირღვა, ეს 14ada3b5d68b1a5a7efe93601c2da16ca4238b8e იმპლემენტაცია არ მუშაობდა, იხ. შესაძლო ამოხსნა: 3fadf6f359b6c0a530cc119a8d3af19291fdc3e1
კითხვები: 0  - მემგონი Liskov-ის პრინციპი აგერიათ ან Demeter-ში, ან SoC-ში. Liskov-ის მთავარი მომენტი არის სუპერ ტიპის სუბ ტიპით ჩანაცვლებადობა, რაც თქვენი პასუციდან არ ჩანს.
შედარება: 20 
ჯამი: 30

**Comment by nikagogibedashvili** [comment]
Liskov-თან დაკავშირებით:
მაგ ჩანაცვლებადობის პრობლემა ჰო ზუსტად ორი SnakeFactory-ს შემთხვევაში
შეიძლება დამდგარიყო? createSnake-ს გადაეცემა ერთადერთი არგუმენტი, რაც
შეიძლება HungrySnake-ის შემთხვევაში საკმარისი არ იყოს. ქულისთვის არ
გეკითხებით, უბრალოდ მაინტერესებს.
