### ISSUE TITLE
Ghost mouse and poison

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#4]
ამჟამად თაგვი იქვე რჩება სადაც გაჩნდება მანამ სანამ გველი არ შეჭამს.
თქვენი ამოცანაა შექმნათ ახალი ლეველი რომელშიც თამაშის დაწყებიდანვე
გველის გარდა გაჩნდება ერთი თაგვი და ერთი შხამი. შემთხვევითი განსხვავებული ინტერვალებით ხან თაგვი და ხან შხამი გაქრებიან და სხვა ადგილზე ამოყოფენ თავს.
1. მოიფიქრეთ დაგჭირდებათ თუ არა ახალი MouseBeing და PoisonBeeing-ის შექმნა - თუ კი მოიფიქრეთ რომელ კლასებს აირჩევთ მშობელ კლასად.
2. დაამატეთ შესაბამისი Populator-ი თითოეულისათვის  - მოიფიქრეთ რომელ კლასებს აირჩევთ მშობელ კლასად.
3. გააერთიანეთ ეს ორი პოულატორი CompositePopulator-ის საშუალებით.
4. შექმენით ახალი ლეველი, მოიფიქრეთ დასახელება და დაამატეთ App-ში შესაბამის ადგილზე.

კითხვები:
1. გაეცით კითხვა 4.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by AnnaGorozia** [comment]
ამოცანის ამოხსნა შეიძლებოდა ახალი MouseBeing და PoisonBeeing-ის შექმნის გარეშე. GhostMousePopulator და GhostPoisonPopulator კლასებში დავიმახსოვრებდი დროს და შემდეგ being ობიექტს, თუკი ის არსებობდა(არ იყო null), "მოვკლავდი", თუმცა უმლ დიაგრამის მიხედვით Populator მხოლოდ ქმნის being ობიექტს და kill-ს კი Universe კლასის ობიექტი იძახებს. ასევე თუ MouseBeing და PoisonBeeing-ებს არ შევქმნიდი, პოპულატორში ყოველ ჯერზე შეიქმნებოდა ახალი being ობიექტი, ამოცანის პირობის თანახმად კი, თაგვმა და საწამვლავმა უბრალოდ ადგილები უნდა შეიცვალონ და არა თავიდან შეიქმნან.

**Comment by gmamaladze** [comment]
@AnnaGorozia 
დავალება: 40 - DRY პრინციპის დარღვევა, GhostBeing - კლსის არარსებობა, იხ. d2ab06f
კითხვები: 30
შედარება: 20
ჯამი: 90
