### ISSUE TITLE
Idea .gitignore entries are missing. User files are checked in.

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#57]
@berolomsa please fix commit cfb78ae
1. .gitignore entries for idea are either wrong or missing
2. workspace.xml and tasks.xml files store user specific settings. Committing them will overwrite other user settings.

Please add something like that to .gitignore. Do not forget to remove "garbage" from git. Use command git rm --cached -r somedir to remove from git but keep file locally. 

```
### Intellij ###

# User-specific stuff:
.idea/workspace.xml
.idea/tasks.xml
.idea/dictionaries

# Sensitive or high-churn files:
.idea/dataSources.ids
.idea/dataSources.xml
.idea/sqlDataSources.xml
.idea/dynamic.xml
.idea/uiDesigner.xml
```

**Comment by berolomsa** [comment]
არ ვიცოდი თუ შეიძლებოდა თორე აქამდეც შევცვლიდი გიტიგნორს

**Comment by gmamaladze** [comment]
:+1:
