### ISSUE TITLE
Swing implementation of maze view

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#7]
ამოცანის მიზანია ალტერნატიული UI-ს იმპლემენტირება სხვა ტექნოლოგისს გამოყენებით.
Swing-ზე დიდი დრო რომ არ დახარჯოთ ჩონჩხის აღება შეიძლება აქედან.
https://github.com/vvulevv/Snake-Java-Console-Game
1. შექმენით SwingViewFactory და შესაბამისი SwingView-ები.
2. App-ში ჩაანაცვლეთ TerminalVewFactory.
3. LevelView-სათვის მოახდინეთ ნულოვანი იმპლემენტაცია, ანუ View რომელიც ლეველების არჩევის ნაცვლად უბრალოდ პირველივე ლეველს აირჩევს და არაფერს გამოაჩნეს.
4. მოახდინათ MazeView-ს იმპლემენტაცია.

კითხვები:
1. გაეცით კითხვა 7.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
2. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by gmamaladze** [comment]
Swing-ზე დიდი დრო რომ არ დახარჯოთ ჩონჩხის აღება შეიძლება აქედან.
https://github.com/vvulevv/Snake-Java-Console-Game

**Comment by GROX13** [comment]
ობსერვერი გამოყენებულია MazePresenter (Observable) - ისა და CellUpdateListener (Observer) - ის შვილობილი კლასების (TerminalMazeViewUpdater, SwingMazeViewUpdater) საურთიერთობოდ. MazePresenter - ში შესაძლებელია setCellUpdateListener(CellUpdateListener listener) მეთოდის გამოძახებით დავარეგისტრიროთ CellUpdateListener (Observer) - ები შემდგომ კი პროგრამის მუშაობისას პრეზენტერი ობსერვერებს შეატყობინებს კონკრეტული უჯრის შიგთავსის მდგომარეობას, დამკვირვებლის (Observer) ვალდებულება კი არის ის, რომ მოახდინოს ამ ცვლილების გრაფიკაში გარდასახვა. ამ შემთხვევაში ობსერვერი გამოყენებულია იმ მიზნით, რომ გრაფიკას თავად არ "ეწვალა" ცვლილებაზე ინფორმაციის მისაღებად და წამდაუწუმ არ ეგზავნა MazePresenter - ისთვის მოთხოვნები კონკრეტული უჯრების შესახებ. ასეთი რეალიზაციით, როგორც უკვე ვთქვი გარკვეული ცვლილების შემთხვევაში თავადვე მოუვა დამკვირვებელს (Observer) ინფორმაცია და იგი ვალდებული იქნება მოახდინოს სათანადო რეაგირება. ასევე Observer - ი ერთ-ერთ მთვარ ნაწილს წარმოადგენს ჩვენთვის კარგად ნაცნობ Model–View–Controller (MVC) არქიტექტურულ პატერნში, რომელის მიხედვითაც არის ეს პროექტი დაგეგმილი.

**Comment by GROX13** [comment]
SnakeGame1 - ში ხდება კითხვა და წერა ტერმინალზე ჩემს შემთხვევაში კი საჭიროა ახალი კლასის გაკეთება, რომელიც JPanel - ის შვილობილი იქნებოდა და მოგვიწევდა public void paint(Graphics graphics); მეთოდის გადატვირთვა, როგორც ეხლა ხდება ჩემს კოდში, რადგან მხოლოდ ჩვენ ვიცით ის, თუ როგორ უნდა მოიქცეს პანელი ხატვისას. რადგანაც სვინგზე გადაწერისას ტერმინალი ზედმეტი გახდებოდა შეცვლა მოგვიწევდა ასევე "მსმენელისა". მოგვიწევდა შეგვექმნა KeyListener ის შვილობილი კლასი, რომელსაც დავარეგისტრირებდით ჩვენს მიერვე შექმნილ JPanel ზე და გავუწერდით შემდეგ მეთოდებს:
-  public void keyPressed(KeyEvent e)
-  public void keyReleased(KeyEvent e)
-  public void keyTyped(KeyEvent e)

რა თქმა უნდა გვეცვლება ხატვის ფუნქციაც, ეს ცვლილება მოხდება ჩვენს მიერ შექმნილ JPanel - ის შვილობილ კლასში public void paint(Graphics graphics); მეთოდში, ამასთანავე მოგვიწევს ამ კლასისთვის ინფორმაციის მიწოდება დაფის შესახებ და შეიძლება ობსერვერ პატერნის გამოყენება ამ შემთხვევაში. სავარაუდოდ ეს არის იმ ცვლილებების სია რომელთა განხორციელებაც მომიწევდა.

**Comment by gmamaladze** [comment]
@GROX13 
დავალება: 50
კითხვები: 30
შედარება: 20
ჯამი: 100
