### ISSUE TITLE
Game over

### ISSUE THREAD

**Issue by gmamaladze** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#8]
ამოცანის მიზანია თამაშის ბოლოს ეკრანის ცენტრში გამოჩნდეს წარწერა.

```
      Game Over
Do you want to play again?
Press Y to play again.
Press N or ESC to quit.
```

Y,N და ESC ღილაკებს უნდა ქონდეთ სასურველი შედეგი.

ამისათვის:
1. უნდა შექმნათ (ან შეცვალოთ) GameOverView 
2. მისი კონკრეტული იმპლემენტაცია GameOverViewTerminal
3. შესაბამისად გააფართოვეთ ViewFactory და TerminalViewFactory 
3. დაამატოთ თამაშის ხელახლა დაწყების ფუნქციონალობა ViewController-ს
- წაიკითხეთ და გაიაზრეთ როგორ არის ჩაფიქრებული ViewController->ViewFactory->View დიზაინი და დაიცავით იგი. 
- კონკრეტული TerminalView-ს იმპლემენტაციისას შეგიძლიათ TerminalLevelView-ს Level-ის არჩევის კოდს გაეცნოთ.

კითხვები:
1. რატომ არ გახდა ამ შემთხვევაში Presenter-ის რეალიზაცია
2. გაეცით კითხვა 8.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
3. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by gmamaladze** [comment]
ამოცანის მიზანია თამაშის ბოლოს ეკრანის ცენტრში გამოჩნდეს წარწერა.
      
      Game Over
Do you want to play again?
Press Y to play again.
Press N or ESC to quit.

Y,N და ESC ღილაკებს უნდა ქონდეთ სასურველი შედეგი.

ამისათვის:
1. უნდა შექმნათ (ან შეცვალოთ) GameOverView 
2. მისი კონკრეტული იმპლემენტაცია GameOverViewTerminal
3. შესაბამისად გააფართოვეთ ViewFactory და TerminalViewFactory 
3. დაამატოთ თამაშის ხელახლა დაწყების ფუნქციონალობა ViewController-ს

* წაიკითხეთ და გაიაზრეთ როგორ არის ჩაფიქრებული ViewController->ViewFactory->View დიზაინი და დაიცავით იგი. 
* კონკრეტული TerminalView-ს იმპლემენტაციისას შეგიძლიათ TerminalLevelView-ს Level-ის არჩევის კოდს გაეცნოთ.

კითხვები:
1. რატომ არ გახდა ამ შემთხვევაში Presenter-ის რეალიზაცია
2. გაეცით კითხვა 8.-ს პაუსხი [ამ კითხვების სიიდან](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-2:-Questions)
3. მოახდინეთ შედარება ამ [Wiki გვერდზე](https://github.com/gmamaladze/FreeUni-SDP-2015-Lab-Realization/wiki/Task-3:-Comparison-with-SnakeGame1)

**Comment by berolomsa** [comment]
პრეზენტერის რეალიზაციის საჭიროება არ არის რადგან ჩემი დავალება მხოლოდ View -ს ეხება და ლოგიკაში ცვლილებებს არ ვახორციელებ

**Comment by gmamaladze** [comment]
@berolomsa 
დავალება: 50
კითხვები: 30
შედარება: 20
ჯამი: 100
